'use client'

import { DownloadIcon } from "lucide-react"
import { Button } from "@/components/ui/button"

export default function DownloadSummaryButton({title,
    summaryText,
    fileName,
    createdAt
}:{
    title:string,
    summaryText:string,
    fileName:string,
    createdAt:string
}){
    const handleDownload=()=>{

        const summaryContent=`# ${title}
Generated Summary
Generated on ${new Date(createdAt).toLocaleDateString()}

${summaryText}

Original File: ${fileName}
Generated by SumUp AI
`
        const blob=new Blob([summaryContent],{type:'text/plain'})
        const url = URL.createObjectURL(blob);
        const link=document.createElement('a');
        link.href=url;
        link.download=`Summary-${(title).replace(/\s+/g,'-')}.txt`;
        document.body.appendChild(link);
        link.click();
        document.body.removeChild(link);
        URL.revokeObjectURL(url);
    }

    return(
        <Button size={'sm'} className="h-8 px-3 bg-rose-100 text-rose-600
         hover:text-rose-700 hover:bg-rose-50" onClick={handleDownload}>
            <DownloadIcon/>
            Download Summary
        </Button>
    )
}
